### ISSUE TITLE
Restructure directories and scripts to better accommodate multiple algorithms along with structure for test code

### ISSUE THREAD

**Issue by chuckwondo** [MAAP-Project/maap-documentation-examples#20]
Since DPS currently supports only 1 image per repository, we can only support a 1 build script within the repository, even though the intent for this repository is to support many algorithms. If we were to maintain a separate build script for each algorithm, then each time one of the algorithms is registered, the DPS image would be built to accommodate _only_ that algorithm, and the other algorithms might no longer function (because the image would no longer contain needed dependencies).

Therefore, the `build.sh` file at the top of this repo should act as a unifying build script that automatically invokes any `build.sh` scripts found in immediate subdirectories (only check 1 level down). That is, it should automatically look for a `build.sh` file at the top of each top-level subdirectory, and for each one found, it should run it.

Each `build.sh` within a subdir should construct its own conda env and populate it with the dependencies specific to the algo within that subdir. This way, when the top-level `build.sh` runs a child `build.sh`, the child script will create a distinct conda env, specific to the algo, and thus should avoid any conflict or interference between algos, each to be run within its own conda env when DPS runs the algo.

For example:

```
./
+-- build.sh
+-- gedi-subset/
|   +-- algorithm_config.yml
|   +-- build.sh
|   +-- environment.yml
|   +-- subset.sh
|   +-- src/
|       +-- subset.py
|       +-- ...
+-- another-algo/
|   +-- algorithm_config.yml
|   +-- build.sh
...
```

In addition, for the `gedi-subset` subdir, move `*.py` files into a `src` subdir as our first step towards better structure to accommodate unit tests (to be added in a separate PR).

## Acceptance Criteria

- Move lines 10 through end of file in `build.sh` to new `gedi-subset/build.sh` (and change relative paths as necessary)
- After the lines kept in `build.sh` (first 9 lines), add logic to iterate over top-level subdirs and for each `build.sh` found at the top of each subdir, execute it
- Move `environment.yml` to `gedi-subset/environment.yml`, as it is specific to `gedi-subset`
- Move `gedi-subset/*.py` to `gedi-subset/src/*.py`
- Move `typings` dir down into `gedi-subset/src` dir
- Move `pyproject.toml` into `gedi-subset` dir

**Comment by jjfrench** [comment]
Opened #19 Restructured Repository
