### ISSUE TITLE
DPS image for gedi-subsetter is missing maap.cfg file

### ISSUE THREAD

**Issue by jjfrench** [MAAP-Project/maap-documentation-examples#44]
## Epic

[#213](https://github.com/NASA-IMPACT/active-maap-sprint/issues/213)

Links to: [#312](https://github.com/NASA-IMPACT/active-maap-sprint/issues/312)

## Description

The image used for the GEDI subsetting algorithm is broken:

```
OSError: No maap.cfg file found. Locations checked: ./maap.cfg; /home/ops/maap.cfg; /maap-py/maap.cfg
ERROR conda.cli.main_run:execute(49): `conda run /app/maap-documentation-examples/gedi-subset/src/gedi_subset/subset.py --verbose --aoi input/GAB-ADM0.geojson --columns agbd,agbd_se,sensitivity,sensitivity_a2` failed. (See above for error)
+ cp _stderr.txt _alt_traceback.txt
```

This appears to be due to use of the following image as specified for the `docker_url` value within the `algorithm_config.yml` file:

```
docker_url: mas.maap-project.org:5000/root/ade-base-images/r:latest
```

Unfortunately, there are no tagged images, so it seems that a recent build of the image introduced this problem.

Sujen suggested we use the following instead:

```
docker_url: mas.dit.maap-project.org/root/maap-workspaces/base_images/r:dit
```

**Comment by chuckwondo** [comment]
Fixed and confirmed that gedi-subset_ubuntu:gedi-subset-0.2.7 runs successfully in DPS.
